[package]
name = "ud3tn-aap"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.43"

[dev-dependencies]
inquire = "0.6.2"
url = "2.4.0"
